   
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    vendor: secvision
    app: kali
    role: verify-src
  name: qty-verify-src-pod
  namespace: secvision
spec:
  containers:
  - image: 172.28.236.251:5000/secvision/kali:3.15
    name: qty-verify-src-pod
    env:
    - name: CODE
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: verify-src-code
    - name: SERVER_HOST
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: secvision-server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---

   
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    vendor: secvision
    app: kali
    role: verify-dst
  name: qty-verify-dst-pod
  namespace: secvision
spec:
  containers:
  - image: 172.28.236.251:5000/secvision/kali:3.15
    name: qty-verify-dst-pod
    env:
    - name: CODE
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: verify-dst-code
    - name: SERVER_HOST
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: secvision-server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---

   
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    vendor: secvision
    app: kali
    role: verify-shell
  name: qty-verify-shell-pod
  namespace: secvision
spec:
  containers:
  - image: 172.28.236.251:5000/secvision/kali:3.15
    name: qty-verify-shell-pod
    env:
    - name: CODE
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: verify-shell-code
    - name: SERVER_HOST
      valueFrom:
        configMapKeyRef:
          name: secvision-cm
          key: secvision-server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---

