apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm

data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maria-dep
    test: 4-4
  name: maria-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria-dep

  template:
    metadata:
      labels:
        app: maria-dep
        test: 4-4
    spec:
      containers:
      - image: mariadb:10
        name: mariadb
        ports:
        - containerPort: 3306

        envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
            name: maria-cm

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: maria-dep
    test: 5-3
  name: maria-svc

spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30006

  type: NodePort
  selector:
    app: maria-dep

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm

data:
  HOST: 'maria-svc'
  USER: 'wp'
  PASSWORD: '123'
  NAME: 'db'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-dep
    test: 4-4
  name: wp-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-dep

  template:
    metadata:
      labels:
        app: wp-dep
        test: 4-4
    spec:
      containers:
      - image: wordpress:5
        name: wordpress
        ports:
        - containerPort: 80

        envFrom:
        - prefix: 'WORDPRESS_DB_'
          configMapRef:
            name: wp-cm
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-dep
    test: 4-4
  name: wp-svc

spec:
  ports:
  - name: http80
    port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: wp-dep


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thinkphp-dep
    test: 4-4
  name: thinkphp-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinkphp-dep

  template:
    metadata:
      labels:
        app: thinkphp-dep
        test: 4-4
    spec:
      containers:
      - image: vulhub/thinkphp:5.0.20
        name: thinkphp-dep
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: thinkphp-dep
    test: 4-4
  name: thinkphp-dep-svc

spec:
  ports:
  - name: http80
    port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: thinkphp-dep


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: euler-dep
    test: 4-5
  name: euler-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: euler-dep

  template:
    metadata:
      labels:
        app: euler-dep
        test: 4-5
    spec:
      containers:
      - image: euleros:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
        name: euleros-dep
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: centos-dep
    test: 4-5
  name: centos-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-dep

  template:
    metadata:
      labels:
        app: centos-dep
        test: 4-5
    spec:
      containers:
      - image: centos:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
        name: centos-dep
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu-dep
    test: 4-5
  name: ubuntu-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-dep

  template:
    metadata:
      labels:
        app: ubuntu-dep
        test: 4-5
    spec:
      containers:
      - image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
        name: ubuntu-dep
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine-dep
    test: 4-5
  name: alpine-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-dep

  template:
    metadata:
      labels:
        app: alpine-dep
        test: 4-5
    spec:
      containers:
      - image: alpine:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
        name: alpine-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-dep
    test: 4-5
    cve: CVE-2017-8291
  name: python-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-dep

  template:
    metadata:
      labels:
        app: python-dep
        test: 4-5
        cve: CVE-2017-8291
    spec:
      containers:
      - image: 172.28.236.251:5000/cve/python:PIL-CVE-2017-8291
        name: python-dep
        command: ["python", "app.py"]
        ports:
          - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-dep
    test: 4-5
  name: python-dep-svc

spec:
  ports:
  - name: python8000
    port: 8000
    protocol: TCP
    targetPort: 8000

  selector:
    app: python-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruby-dep
    test: 4-5
    cve: CVE-2017-17405
  name: ruby-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-dep

  template:
    metadata:
      labels:
        app: ruby-dep
        test: 4-5
        cve: CVE-2017-17405
    spec:
      containers:
      - image: 172.28.236.251:5000/cve/ruby:CVE-2017-17405
        name: ruby-dep
        command: ["ruby", "web.rb", "-p", "8080", "-o", "0.0.0.0"]
        ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruby-dep
    test: 4-5
  name: ruby-dep-svc

spec:
  ports:
  - name: ruby8080
    port: 8080
    protocol: TCP
    targetPort: 8080

  selector:
    app: ruby-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-dep
    test: 4-5
  name: redis-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dep

  template:
    metadata:
      labels:
        app: redis-dep
        test: 4-5
        user: 'default'
        password: '123456'
    spec:
      containers:
      - image: bitnami/redis:latest
        name: redis-dep
        env:
          - name: REDIS_PASSWORD
            value: '123456'
        ports:
          - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-dep
    test: 5-3
  name: redis-dep-svc

spec:
  ports:
  - name: redis6379
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 30079

  type: NodePort
  selector:
    app: redis-dep


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat-dep
    test: 4-5
  name: tomcat-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-dep

  template:
    metadata:
      labels:
        app: tomcat-dep
        test: 4-5
        user: 'user'
        password: '123456'
    spec:
      containers:
      - image: bitnami/tomcat:latest
        name: tomcat-dep
        env:
          - name: TOMCAT_USERNAME
            value: 'user'
          - name: TOMCAT_PASSWORD
            value: '123456'
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat-dep
    test: 4-5
  name: tomcat-dep-svc

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

  selector:
    app: tomcat-dep


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-dep
    test: 4-5
    cve: cve-2017-14849
  name: nodejs-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-dep

  template:
    metadata:
      labels:
        app: nodejs-dep
        test: 4-5
        cve: cve-2017-14849
    spec:
      containers:
      - image: 172.28.236.251:5000/cve/nodejs:CVE-2017-14849
        name: nodejs-dep
        command: ["npm", "run", "start"]
        ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-dep
    test: 4-5
  name: nodejs-dep-svc

spec:
  ports:
  - name: nodejs3000
    port: 3000
    protocol: TCP
    targetPort: 3000

  selector:
    app: nodejs-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sshd-dep
    test: 4-5
  name: sshd-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-dep

  template:
    metadata:
      labels:
        app: sshd-dep
        test: 4-5
        user: 'root'
        password: '123456'
    spec:
      containers:
      - image: 172.28.236.251:5000/sshd:weakpwd
        name: sshd-dep
        command: ["/usr/sbin/sshd", "-D"]
        ports:
          - containerPort: 22
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sshd-dep
    test: 5-3
  name: sshd-dep-svc

spec:
  selector:
    app: sshd-dep
  ports:
  - name: sshd22
    port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30022

  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-dep
    test: 4-5
  name: php-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-dep

  template:
    metadata:
      labels:
        app: php-dep
        test: 4-5
        user: 'root'
        password: 'root'
    spec:
      containers:
      - image: 172.28.236.251:5000/cve/php:CVE-2019-11043
        name: sshd-dep
        ports:
          - containerPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-dep
    test: 4-5
  name: php-dep-svc

spec:
  selector:
    app: php-dep
  ports:
  - name: php9000
    port: 9000
    protocol: TCP
    targetPort: 9000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-10m-pv

spec:
  storageClassName: host-test
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /root

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-5m-pvc

spec:
  storageClassName: host-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: host-pvc-pod
  labels:
    app: nginx-pod
    test: 5-8
spec:
  volumes:
  - name: host-pvc-vol
    persistentVolumeClaim:
      claimName: host-5m-pvc

  containers:
    - name: ngx-pvc-pod
      image: nginx:latest
      ports:
      - containerPort: 80
      volumeMounts:
      - name: host-pvc-vol
        mountPath: /tmp

---

apiVersion: v1
kind: Pod
metadata:
  name: host-sysadmin-pod
  labels:
    app: nginx-pod
    test: 5-8
spec:

  containers:
    - name: ngx-sysadmin-pod
      image: nginx:alpine
      ports:
      - containerPort: 80
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_ADMIN"]

---

apiVersion: v1
kind: Pod
metadata:
  name: host-privileged-pod
  labels:
    app: nginx-pod
    test: 5-8
spec:

  containers:
    - name: ngx-privileged-pod
      image: nginx:alpine
      ports:
      - containerPort: 80
      securityContext:
        privileged: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernal-dep
  labels:
    app: kernal-dep
    test: 5-8
    cve: cve-2020-14386
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernal-dep

  template:
    metadata:
      labels:
        app: kernal-dep
        test: 5-8
        cve: cve-2020-14386
    spec:
      containers:
      - image: 172.28.236.251:5000/cve/kernal:cve-2020-14386
        name: kernal-dep
        securityContext:
          privileged: true



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
  labels:
    app: grafana-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dep

  template:
    metadata:
      labels:
        app: grafana-dep
        test: 4-4

    spec:
      containers:
      - image: grafana/grafana:latest
        name: grafana-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-dep
  labels:
    app: rsyslog-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog-dep

  template:
    metadata:
      labels:
        app: rsyslog-dep
        test: 4-4

    spec:
      containers:
      - image: rsyslog/syslog_appliance_alpine:latest
        name: rsyslog-dep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-dep
  labels:
    app: supervisor-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor-dep

  template:
    metadata:
      labels:
        app: supervisor-dep
        test: 4-4

    spec:
      containers:
      - image: okteto/supervisor:0.3.0
        name: supervisor-dep
        ports:
          - containerPort: 9001
        command: [ "/usr/local/bin/supervisor" ]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowsocks-dep
  labels:
    app: shadowsocks-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadowsocks-dep

  template:
    metadata:
      labels:
        app: shadowsocks-dep
        test: 4-4

    spec:
      containers:
      - image: dockage/shadowsocks-server:latest
        name: shadowsocks-dep
        ports:
        - containerPort: 8388
        env:
          - name: SS_PASSWORD
            value: 'ssp@ss'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
  labels:
    app: httpd-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-dep

  template:
    metadata:
      labels:
        app: httpd-dep
        test: 4-4

    spec:
      containers:
      - image: httpd:latest
        name: httpd-dep
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-dep
  labels:
    app: wildfly-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly-dep

  template:
    metadata:
      labels:
        app: wildfly-dep
        test: 4-4

    spec:
      containers:
      - image: bitnami/wildfly:latest
        name: wildfly-dep
        ports:
        - containerPort: 8080
        - containerPort: 9990
        env:
          - name: WILDFLY_PASSWORD
            value: "12345678"



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfire-dep
  labels:
    app: openfire-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfire-dep

  template:
    metadata:
      labels:
        app: openfire-dep
        test: 4-4

    spec:
      containers:
      - image: nasqueron/openfire:4.8.0
        name: openfire-dep
        ports:
        - containerPort: 5222
        - containerPort: 9090
        - containerPort: 7777


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-dep
  labels:
    app: postgresql-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-dep

  template:
    metadata:
      labels:
        app: postgresql-dep
        test: 4-4

    spec:
      containers:
      - image: bitnami/postgresql:12
        name: postgresql-dep
        env:
          - name: POSTGRESQL_PASSWORD
            value: "123456"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dep
  labels:
    app: mongo-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-dep

  template:
    metadata:
      labels:
        app: mongo-dep
        test: 4-4

    spec:
      containers:
      - image: mongo:latest
        name: mongo-dep
        ports:
        - containerPort: 8081


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-dep
  labels:
    app: influxdb-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-dep

  template:
    metadata:
      labels:
        app: influxdb-dep
        test: 4-4

    spec:
      containers:
      - image: influxdb:latest
        name: influxdb-dep
        ports:
        - containerPort: 8086

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
  labels:
    app: spring-dep
    test: 4-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-dep

  template:
    metadata:
      labels:
        app: spring-dep
        test: 4-4

    spec:
      containers:
      - image: springio/gs-spring-boot-docker:latest
        name: spring-dep
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-dep
  labels:
    app: redhat-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redhat-dep

  template:
    metadata:
      labels:
        app: redhat-dep
        test: 4-5

    spec:
      containers:
      - image: redhat/ubi8:latest
        name: redhat-dep
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclelinux-dep
  labels:
    app: oraclelinux-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: oraclelinux-dep

  template:
    metadata:
      labels:
        app: oraclelinux-dep
        test: 4-5

    spec:
      containers:
      - image: oraclelinux:9
        name: oraclelinux-dep
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazonlinux-dep
  labels:
    app: amazonlinux-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazonlinux-dep

  template:
    metadata:
      labels:
        app: amazonlinux-dep
        test: 4-5

    spec:
      containers:
      - image: amazonlinux:latest
        name: amazonlinux-dep
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-dep
  labels:
    app: fedora-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-dep

  template:
    metadata:
      labels:
        app: fedora-dep
        test: 4-5

    spec:
      containers:
      - image: fedora:latest
        name: fedora-dep
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-dep
  labels:
    app: debian-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-dep

  template:
    metadata:
      labels:
        app: debian-dep
        test: 4-5

    spec:
      containers:
      - image: debian:sid
        name: debian-dep
        command: [ "bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon-dep
  labels:
    app: photon-dep
    test: 4-5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon-dep

  template:
    metadata:
      labels:
        app: photon-dep
        test: 4-5

    spec:
      containers:
      - image: photon:latest
        name: photon-dep
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 3600; done;" ]
